'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useRef,useState} from 'react';
import {AnimatePresence, motion, useReducedMotion} from 'framer-motion';
import {ArrowUpRight, ArrowDown, Play, X, Menu, Pause} from 'lucide-react';
import projects from './projects.json';
import FeaturedPlayer from './FeaturedPlayer';
import VideoThumbnail from './VideoThumbnail';

export function Navigation(){const path=usePathname();const [open,setOpen]=useState(false);return <header className="navigation"><Link href="/" className="wordmark" onClick={()=>setOpen(false)} aria-label="HalftoneMotion home">HalftoneMotion</Link><button className="menu-toggle" aria-expanded={open} aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'nav-links open':'nav-links'}>{[['/','Home'],['/work','Work'],['/about','About'],['/process','Process'],['/experiments','Play']].map(([href,label])=><Link key={href} href={href} aria-current={path===href?'page':undefined} onClick={()=>setOpen(false)}>{label}</Link>)}<Link href="/contact" className="nav-contact" onClick={()=>setOpen(false)}>Let’s talk <ArrowUpRight size={16}/></Link></nav></header>}
export function Reveal({children,className='',delay=0}:{children:React.ReactNode,className?:string,delay?:number}){const reduce=useReducedMotion();return <motion.div className={className} initial={reduce?false:{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.1}} transition={{duration:.6,delay:reduce?0:delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}
export function Film({id,title,hero=false}:{id:string,title:string,hero?:boolean}){const dialog=useRef<HTMLDialogElement>(null);const [playing,setPlaying]=useState(false);return <><button className={`film ${hero?'hero-film':''}`} onClick={()=>{setPlaying(true);dialog.current?.showModal()}} aria-label={`Watch ${title}`}><VideoThumbnail id={id} title={title} eager={hero}/><span className="film-shade"/><span className="film-top mono"><span>{hero?'IN THE SPOTLIGHT':'PLAY FILM'}</span><span>↗</span></span><span className="play-circle"><Play size={24} fill="currentColor"/></span><span className="film-bottom"><span>{title}</span><span className="mono">{hero?'WATCH PROJECT':'VIEW FILM'}</span></span></button><dialog ref={dialog} className="film-dialog" onClose={()=>setPlaying(false)} onClick={e=>{if(e.target===dialog.current)dialog.current.close()}}><button className="close-film" onClick={()=>dialog.current?.close()} aria-label="Close video"><X/></button>{playing&&<iframe src={`https://www.youtube-nocookie.com/embed/${id}?autoplay=1&rel=0`} title={title} allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen/>}<a href={`https://www.youtube.com/watch?v=${id}`} target="_blank" rel="noreferrer">Watch on YouTube <ArrowUpRight size={15}/></a></dialog></>}
export function Hero(){return <section className="hero wrap"><div className="hero-meta mono"><span>INDEPENDENT MOTION DESIGNER</span><span>WORKING WORLDWIDE</span></div><h1><span className="title-line">GOOD IDEAS.</span><span className="title-line second">GREAT <span className="kinetic">MOTION<span className="keyframe" aria-hidden="true"/></span>.</span></h1><div className="hero-lower"><div className="hero-intro"><span className="eyebrow">ATHARV / HALFTONEMOTION</span><p>I turn complex products and good stories into motion you can’t scroll past.</p><Link className="button button-lime" href="/work">Explore my work <ArrowDown size={18}/></Link></div><FeaturedPlayer/></div></section>}
export function WorkGrid({featured=false,lyrical=false}:{featured?:boolean,lyrical?:boolean}){const filter=lyrical?'lyrical':'commercial';const visible=featured?projects.filter(p=>p.type==='commercial').slice(0,4):projects.filter(p=>p.type===filter);return <section className="wrap section" id="work"><Reveal className="section-heading"><div><span className="eyebrow">01 / SELECTED WORK</span><h2>{featured?'Proof in motion.':lyrical?'Rhythm. Type. Play.':'The work.'}</h2></div>{featured?<Link className="text-link" href="/work">Commercial work <ArrowUpRight size={20}/></Link>:<p>{lyrical?'Kinetic typography and lyrical films that move to their own beat.':'Product stories, SaaS explainers, and commercial launch films.'}</p>}</Reveal><div className="work-grid">{visible.map((p,i)=><Reveal key={`${filter}-${p.id}`} className="project" delay={(i%2)*.12}><Film id={p.id} title={p.title}/><div className="project-caption"><h3>{p.title}</h3><span className="mono">{p.tag} / {String(i+1).padStart(2,'0')}</span></div></Reveal>)}</div></section>}
const steps=[['The idea comes first.','Project kickoff','We get clear on your brand, audience, and what the video needs to do. Share your assets and references; together we shape the script and visual direction.'],['Then we make it move.','Animation & sound','Approved designs become carefully timed animation. Typography, product interactions, voiceover, and sound design work together, frame by frame.'],['Fine-tune. Final render.','Revisions & delivery','Review the draft with timestamped feedback. I refine the details and deliver the final video in the agreed formats, ready for your launch.']];
export function Process(){const reduce=useReducedMotion();const [active,setActive]=useState(0);return <section className="section process-section" id="process"><div className="wrap"><Reveal className="section-heading"><div><span className="eyebrow">02 / THE PROCESS</span><h2>From first thought<br/>to final frame.</h2></div><p>A clear creative process.<br/>You’re part of it at every stage.</p></Reveal><div className="process-layout"><div className="process-tabs" role="tablist" aria-label="Production stages">{steps.map((s,i)=><button key={s[1]} role="tab" id={`step-${i}`} aria-selected={active===i} aria-controls="process-panel" tabIndex={active===i?0:-1} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowRight'||e.key==='ArrowUp'||e.key==='ArrowLeft'){e.preventDefault();const n=(active+(e.key==='ArrowDown'||e.key==='ArrowRight'?1:2))%3;setActive(n);document.getElementById(`step-${n}`)?.focus()}}} onClick={()=>setActive(i)}><span className="mono">0{i+1}</span><span>{s[1]}</span><ArrowUpRight size={22}/></button>)}</div><div role="tabpanel" id="process-panel" aria-labelledby={`step-${active}`} className="process-panel"><span className="giant-number" aria-hidden="true">0{active+1}</span><AnimatePresence mode="wait" initial={false}><motion.div key={active} className="process-copy" initial={{opacity:0,y:reduce?0:14}} animate={{opacity:1,y:0}} exit={{opacity:0,y:reduce?0:-8}} transition={{duration:reduce?0:.24,ease:[.22,1,.36,1]}}><span className="eyebrow">FRAME 0{active+1} / 03</span><h3>{steps[active][0]}</h3><p>{steps[active][2]}</p><div className="step-progress" aria-hidden="true">{steps.map((_,i)=><span key={i} className={i<=active?'filled':''}/>)}</div></motion.div></AnimatePresence></div></div></div></section>}
export function Reviews(){return <section className="wrap section"><span className="eyebrow">03 / IN GOOD COMPANY</span><div className="quotes"><Reveal><blockquote>“I needed a promo video for my app and halftonemotion delivered it with great video quality in just a few days at a reasonable price.”</blockquote><div className="quote-person"><img src="/reviews/akil.jpg" alt=""/><p>Akil Gurram<span>Founder of WTM</span></p></div></Reveal><Reveal><blockquote>“They are highly responsive, communicate well, and take genuine ownership of their work.”</blockquote><div className="quote-person"><img src="/reviews/rhythm.jpg" alt=""/><p>Rhythm Shandlya<span>Founder of Vionna</span></p></div></Reveal></div></section>}
export function FAQ(){const qs=[['How long does a project take?','A standard 60-second animation typically takes 1–2 weeks. We agree on the schedule and review milestones before production starts.'],['What do you need to get started?','Your brief, brand assets, product designs or Figma links, and a few references. A 50% upfront payment starts production.'],['Can you help with the script?','Yes. Bring an existing script, a rough idea, or just the product. We develop the narrative before moving into animation.'],['How do revisions work?','You review the draft and leave consolidated, timestamped feedback. The number of included rounds and any additional fees are agreed in your project scope.'],['Do you work with agencies?','Yes. White-label production is available for marketing, branding, and advertising agencies, with confidentiality arrangements agreed before work begins.']];return <section className="wrap section faq"><div><span className="eyebrow">THE PRACTICAL STUFF</span><h2>A few answers.</h2></div><div>{qs.map(([q,a],i)=><details key={q}><summary><span className="mono">0{i+1}</span>{q}<span className="plus">+</span></summary><p>{a}</p></details>)}</div></section>}
export function Footer(){return <footer><div className="wrap"><div className="footer-top"><span className="eyebrow">HAVE SOMETHING IN MIND?</span><span className="mono">LET’S MAKE IT MOVE.</span></div><Link href="/contact" className="footer-cta">Your next<br/>great move.<ArrowUpRight/></Link><div className="footer-bottom"><Link href="/" className="wordmark">HalftoneMotion</Link><div><a href="mailto:halftonemotion@gmail.com">Email <ArrowUpRight size={14}/></a><a href="https://www.instagram.com/halftonemotion/" target="_blank" rel="noreferrer">Instagram <ArrowUpRight size={14}/></a><Link href="/faq">FAQ</Link></div><span className="mono">© {new Date().getFullYear()} HALFTONEMOTION</span></div></div></footer>}
